/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoteoria;

/**
 *
 * @author David
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JTextField();
        BTN_evaluar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 270, -1));

        BTN_evaluar.setText("Evaluar expresión regular");
        BTN_evaluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_evaluarMouseClicked(evt);
            }
        });
        getContentPane().add(BTN_evaluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jButton2.setText("Cargar archivo de texto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoteoria/fondo para el proyecto.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_evaluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_evaluarMouseClicked
        /*pendiente de saber si vamos a hacer las validaciones de la cadena aqui o en otra clase
         pero en primera instancia las wa dejar aqui
         */
        String expresion = texto.getText();
        boolean abc = true, binario = false;
        if (expresion.contains("a") && expresion.contains("b") && expresion.contains("c") && !expresion.contains("0") && !expresion.contains("1")) {
            abc = true;
        } else {
            abc = false;
            if (expresion.contains("1") && expresion.contains("0") && !expresion.contains("a") && !expresion.contains("b") && !expresion.contains("c")) {
                binario = true;
            }
        }
        
        Evaluacion ev= new Evaluacion(expresion);
        System.out.println("abc: " + abc + " binar :" + binario);
        System.out.println("la expresion ingresada al ser evaluada,\nse determinó que:"
                + " \nEvaluacion 2: "+ev.problema2()+"\nEvaluacion 3: "+ev.problema3());
        System.out.println("Problema1:" + ev.problema1());
        System.out.println("Problema4:" + ev.problema4());
    }//GEN-LAST:event_BTN_evaluarMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String expresion = texto.getText();
        AdministrarTexto at = new AdministrarTexto();
        at.cargarArchivo();
        expresion = at.getDatos();
        texto.setText(expresion);

    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_evaluar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
